//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkForDats
{
    using System;
    using System.Collections.Generic;
    
    public partial class datsUsers
    {
        public int UserID { get; set; }
        public string UserCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PIN { get; set; }
        public string Phone { get; set; }
        public string PhoneExtension { get; set; }
        public string CellPhone { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string userRecordStatus { get; set; }
        public Nullable<System.DateTime> userCreationDate { get; set; }
        public string userCreatedBy { get; set; }
        public Nullable<System.DateTime> userUpdatedDate { get; set; }
        public string userUpdatedBy { get; set; }
        public int DriverID { get; set; }
        public string DriverNumber { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string HandheldPrivateID { get; set; }
        public string Pager { get; set; }
        public int CurrentTruckID { get; set; }
        public string TruckNumber { get; set; }
        public string VehicleYear { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string VIN { get; set; }
        public int UnitsOnTruck { get; set; }
        public string TruckStatus { get; set; }
        public Nullable<int> currenttrailerid { get; set; }
        public int trckCapacity { get; set; }
        public string TrailerNumber { get; set; }
        public Nullable<int> trlrCapacity { get; set; }
        public int trckLastLocationID { get; set; }
        public Nullable<System.DateTime> trckLastLocationDateTime { get; set; }
        public string LocationShortName { get; set; }
        public string FuelCard1Name { get; set; }
        public string FuelCard1Number { get; set; }
        public string FuelCard2Name { get; set; }
        public string FuelCard2Number { get; set; }
        public string FuelCard3Name { get; set; }
        public string FuelCard3Number { get; set; }
        public string FuelCard4Name { get; set; }
        public string FuelCard4Number { get; set; }
        public int LastRunNumber { get; set; }
        public string ScannerID { get; set; }
        public string DriversLicenseState { get; set; }
        public string DriversLicenseNumber { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string LodgingCard { get; set; }
        public int CurrentPayPeriod { get; set; }
        public int drvrLastLocationID { get; set; }
        public Nullable<System.DateTime> drvrLastLocationDate { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
